### ISSUE TITLE
the compute container fails to start, Failed to start Heat Docker Agent Container.

### ISSUE THREAD

**Issue by weshayutin** [redhat-openstack/ansible-role-tripleo-overcloud-prep-containers#1]
```
parameter_defaults:
  NovaImage: atomic-image
  # Defaults to 'tripleoupstream'.  Specify a local docker registry
  # Example: 192.0.2.1:8787/tripleoupstream
  DockerNamespace: 192.168.24.1:8787/tripleoupstream
  # Enable local Docker registry
  DockerNamespaceIsRegistry: true
  DockerAgentImage: heat-docker-agents:newton
  # Docker containers
  DockerNovaComputeImage: centos-binary-nova-compute:newton
  DockerLibvirtImage: centos-binary-nova-libvirt:newton
  DockerOpenvswitchImage: centos-binary-neutron-openvswitch-agent:newton
  DockerOvsVswitchdImage: centos-binary-openvswitch-vswitchd:newton
  DockerOpenvswitchDBImage: centos-binary-openvswitch-db-server:newton
```

`openstack overcloud deploy --templates /home/stack/tripleo-heat-templates --libvirt-type qemu --control-flavor oooq_control --compute-flavor oooq_compute --ceph-storage-flavor oooq_ceph --timeout 90 -e /home/stack/tripleo-heat-templates/environments/docker.yaml -e /home/stack/tripleo-heat-templates/environments/docker-network.yaml -e /home/stack/tripleo-heat-templates/environments/docker-network-isolation.yaml -e /home/stack/tripleo-heat-templates/environments/net-single-nic-with-vlans.yaml -e /home/stack/network-environment.yaml -e /home/stack/tripleo-heat-templates/environments/low-memory-usage.yaml --ntp-server pool.ntp.org`

[compute_journal.txt](https://github.com/redhat-openstack/ansible-role-tripleo-overcloud-prep-containers/files/592397/compute_journal.txt)
